version: 2.1

orbs:
    python: circleci/python@0.2.1

jobs:
    build:
        executor: python/default
        steps:
            - checkout
            - python/load-cache
            - python/install-deps
            - python/save-cache
            - run: 
                command: python3 python/bot.py $ZENDESK_LOGIN $ZENDESK_URL $VIEW_ID_CLOUD $SLACK_CHANNEL
                name: "Check Support Team Tickets"
workflows:
    version: 2
    daily:
        triggers:
            - schedule:
                cron: "0 16 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs: 
            - build